name: Organization CI

on:
  push:
    branches: main
  
jobs:
  build:
    runs-on: ubuntu-latest
steps:
  – name: Checkout repository
uses: actions/checkout@v3
– name: Read package.json
id: package
with:
  path: ./package.json
  – name: Echo package.json
  run:
    echo “${{ steps.package.outputs.content }}”
